version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5001:4200'

  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
      - certbot-etc:/etc/letsencrypt:rw
      - certbot-var:/var/www/certbot:rw
    ports:
      - '80:80' 
      - '443:443'
volumes:
  certbot-etc:
  certbot-var:
