
version: '3.8'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - DEFAULT_HOST=app.dywetrading.com

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=app.dywetrading.com
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=app.dywetrading.com
      - LETSENCRYPT_EMAIL=your-email@example.com
    ports:
      - '5000:5000'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=app.dywetrading.com
      - VIRTUAL_PORT=4200
      - LETSENCRYPT_HOST=app.dywetrading.com
      - LETSENCRYPT_EMAIL=your-email@example.com
    ports:
      - '4200:4200'

